"""Build the direct coherent ZrO2(111)//Na3LaCl6(0001) interface.

The direct 1x1 model is the primary small-cell reference model.  The ZrO2
(111) surface basis generated by ASE has gamma=60 deg; it is converted to an
exactly equivalent gamma=120 deg basis by B -> B-A so it is compatible with
the hexagonal Na3LaCl6 surface basis.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from ase.io import write

from config import (
    A_NA3LACL6_EXPECTED,
    A_ZRO2_EXPECTED,
    DIRECT_DIR,
    INTERFACE_GAP,
    MAX_APPLIED_STRAIN,
    MAX_MODEL_ATOMS,
    MIN_INTERATOMIC_DISTANCE,
    NA3LACL6_CIF,
    NA3LACL6_LAYERS,
    REGISTRY_OFFSETS,
    STRAIN_MODEL,
    VACUUM,
    ZRO2_CIF,
    ZRO2_FLIP_INTERFACE_SIDE,
    ZRO2_LAYERS,
)
from hetero_utils import (
    apply_fractional_xy_translation,
    apply_strain_model,
    build_surface_slab,
    check_expected_lattice,
    combine_two_slabs,
    convert_hex_surface_basis_to_120,
    count_species,
    flip_slab_z,
    load_atoms,
    minimum_periodic_distance,
    surface_cell_metrics,
    write_json,
)


def build_one_registry(fx: float, fy: float):
    zro2_bulk = load_atoms(ZRO2_CIF)
    hex_bulk = load_atoms(NA3LACL6_CIF)

    zro2 = build_surface_slab(
        zro2_bulk,
        (1, 1, 1),
        ZRO2_LAYERS,
    )
    hex = build_surface_slab(
        hex_bulk,
        (0, 0, 1),
        NA3LACL6_LAYERS,
    )

    # Convert the cubic (111) 60-degree primitive basis to an equivalent
    # 120-degree basis; vector lengths and area are unchanged.
    zro2 = convert_hex_surface_basis_to_120(zro2)

    if ZRO2_FLIP_INTERFACE_SIDE:
        zro2 = flip_slab_z(zro2)

    zro2, hex, strain = apply_strain_model(
        reference=zro2,
        film=hex,
        model=STRAIN_MODEL,
    )

    if strain["max_abs_strain"] > MAX_APPLIED_STRAIN + 1e-12:
        raise RuntimeError(
            f"Applied in-plane strain {strain['max_abs_strain']*100:.3f}% "
            f"exceeds MAX_APPLIED_STRAIN={MAX_APPLIED_STRAIN*100:.2f}%"
        )

    # Apply the chosen in-plane registry to the upper Na3LaCl6 slab.
    hex = apply_fractional_xy_translation(hex, fx, fy)

    hetero, physical_height = combine_two_slabs(
        lower=zro2,
        upper=hex,
        gap=INTERFACE_GAP,
        vacuum=VACUUM,
    )

    min_dist = minimum_periodic_distance(hetero)
    if min_dist < MIN_INTERATOMIC_DISTANCE:
        raise RuntimeError(
            f"Registry ({fx:.6f}, {fy:.6f}) gives minimum periodic distance "
            f"{min_dist:.3f} A < {MIN_INTERATOMIC_DISTANCE:.3f} A"
        )

    metrics = surface_cell_metrics(hetero)
    species = count_species(hetero)

    # Direct theoretical mismatch from the requested bulk parameters.
    z111 = A_ZRO2_EXPECTED * np.sqrt(2.0)
    direct_mismatch = (z111 - A_NA3LACL6_EXPECTED) / A_NA3LACL6_EXPECTED

    return hetero, {
        "registry_fractional": [float(fx), float(fy)],
        "atom_count": int(len(hetero)),
        "species": species,
        "surface_cell_a": metrics["a"],
        "surface_cell_b": metrics["b"],
        "surface_cell_gamma_deg": metrics["gamma"],
        "surface_area_A2": metrics["area"],
        "physical_stack_height_A": physical_height,
        "vacuum_gap_A": VACUUM,
        "interface_gap_A": INTERFACE_GAP,
        "minimum_periodic_distance_A": min_dist,
        "strain_model": STRAIN_MODEL,
        **strain,
        "theoretical_zro2_111_A": z111,
        "theoretical_direct_mismatch": direct_mismatch,
        "zro2_expected_lattice_check": check_expected_lattice(
            zro2_bulk, A_ZRO2_EXPECTED, "ZrO2 bulk"
        ),
        "na3lacl6_expected_lattice_check": check_expected_lattice(
            hex_bulk, A_NA3LACL6_EXPECTED, "Na3LaCl6 bulk"
        ),
        "pbc": [True, True, True],
    }


def main() -> int:
    print("=" * 78)
    print("DIRECT INTERFACE: ZrO2(111) // Na3LaCl6(0001)")
    print("=" * 78)

    print(f"ZrO2 layers      : {ZRO2_LAYERS}")
    print(f"Na3LaCl6 layers  : {NA3LACL6_LAYERS}")
    print(f"Interface gap    : {INTERFACE_GAP:.2f} A")
    print(f"Vacuum gap       : {VACUUM:.2f} A")
    print(f"Strain model     : {STRAIN_MODEL}")
    print(f"Registry count   : {len(REGISTRY_OFFSETS)}")

    summaries = []

    for idx, (fx, fy) in enumerate(REGISTRY_OFFSETS, start=1):
        print("\n" + "-" * 78)
        print(f"Registry {idx}: ({fx:.6f}, {fy:.6f})")

        hetero, meta = build_one_registry(fx, fy)

        if len(hetero) > MAX_MODEL_ATOMS:
            raise RuntimeError(
                f"Direct registry generated {len(hetero)} atoms > MAX_MODEL_ATOMS={MAX_MODEL_ATOMS}"
            )

        name = f"Hetero_Direct_registry_{idx:02d}.cif"
        xyz_name = f"Hetero_Direct_registry_{idx:02d}.xyz"
        json_name = f"Hetero_Direct_registry_{idx:02d}.json"

        write(DIRECT_DIR / name, hetero)
        write(DIRECT_DIR / xyz_name, hetero)
        write_json(DIRECT_DIR / json_name, meta)

        print(f"Atoms             : {meta['atom_count']}")
        print(f"Cell a,b          : {meta['surface_cell_a']:.6f}, {meta['surface_cell_b']:.6f} A")
        print(f"Cell gamma        : {meta['surface_cell_gamma_deg']:.3f} deg")
        print(f"Minimum distance  : {meta['minimum_periodic_distance_A']:.3f} A")
        print(f"Max applied strain: {meta['max_abs_strain']*100:.3f}%")
        print(f"Saved             : {name}")

        summaries.append(meta)

    # Keep a backward-compatible canonical name for registry 1.
    canonical = DIRECT_DIR / "Hetero_Direct_ZrO2_111_Na3LaCl6_0001.cif"
    canonical_xyz = DIRECT_DIR / "Hetero_Direct_ZrO2_111_Na3LaCl6_0001.xyz"
    registry1 = DIRECT_DIR / "Hetero_Direct_registry_01.cif"
    registry1_xyz = DIRECT_DIR / "Hetero_Direct_registry_01.xyz"
    if registry1.exists():
        canonical.write_bytes(registry1.read_bytes())
    if registry1_xyz.exists():
        canonical_xyz.write_bytes(registry1_xyz.read_bytes())

    report = {
        "model": "direct coherent interface",
        "orientation": "ZrO2(111)//Na3LaCl6(0001)",
        "registry_count": len(summaries),
        "registries": summaries,
    }
    write_json(DIRECT_DIR / "direct_summary.json", report)

    print("\n" + "=" * 78)
    print("DIRECT BUILD COMPLETED")
    print("=" * 78)
    print("Canonical CIF:")
    print(canonical)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
